#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    split_name = s.split(" ")
    cap_name = []
    for name in split_name:
        cap_name.append(name.capitalize())
    return " ".join(cap_name)
#return " ".join([name.capitalize() for name in s.split(" ")])

if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    #fptr.write(result + '\n')
    print(str(result) + '\n')

    #fptr.close()
