#!/bin/python3
def count_substring(string, sub_string):
    all = 0
    for i in range(0, len(string) - len(sub_string) + 1):
        all += (string[i:len(sub_string) + i]).count(sub_string)
    return all


if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()

    count = count_substring(string, sub_string)
    print(count)