#!/bin/python3
def split_and_join(line):
    # write your code here
    r = "-".join(line.split())
    return r


if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)