#!/bin/python3
import textwrap

def wrap(string, max_width):
    s_wrap = textwrap.wrap(string, max_width)
    return '\n'.join(s_wrap)

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

